name: Build and Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Docker Compose
        run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      # Step 3: Build and tag the Docker image
      - name: Build and Tag Docker Image
        run: |
          docker build -t your-docker-hub-username/frontend:latest -t your-docker-hub-username/frontend:v1.0 -f ./frontend/Dockerfile .
          docker build -t your-docker-hub-username/backend:latest -t your-docker-hub-username/backend:v1.0 -f ./backend/Dockerfile .


          docker tag dhananjaylakkawar/frontend:latest dhananjaylakkawar/myserver:v1.0
          docker tag dhananjaylakkawar/api:latest dhananjaylakkawar/myserver_back:v1.0

      # Step 4: Push the image to Docker Hub
      - name: Push to Docker Hub
        run: |
         docker push dhananjaylakkawar/frontend:latest
         docker push dhananjaylakkawar/myserver:v1.0
         docker push dhananjaylakkawar/api:latest
         docker push dhananjaylakkawar/myserver_back:v1.0
      # Step 5: Set up SSH agent to connect to EC2 instance
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 6: Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd  ~/DC_react-node-mysql
            docker-compose down  
            docker-compose pull  
            docker-compose up -d  
          EOF
